language: rust

os: linux
dist: bionic
cache:
  directories:
    - /home/travis/.cargo

rust:
  - nightly

script:
  - cargo build --verbose
  - cargo test -- --nocapture

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - lib32z1-dev
      - libedit-dev
      - binutils-dev
      - libiberty-dev
      - libssl-dev

env:
  global:
    - RUSTFLAGS="-C link-dead-code -C target-cpu=native -l ffi"

before_cache:
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  - rm -rf /home/travis/.cargo/registry

before_install:
  - sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
  - sudo apt-get -q update
  - sudo apt-get -y install llvm-8 llvm-8-dev libllvm8


after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
