//! This file is autogenerated by ast-generator. Do not modify!

use crate::CSTNode;
use common::{ModPath, ModulePath};
use parser::{SyntaxToken, ParseResult};
use smol_str::SmolStr;
use syntax::{kind::SyntaxKind, language::GelixLang};
use std::rc::Rc;
